### ISSUE TITLE
the backup-path should default to current working directory

### ISSUE THREAD

**Issue by haidangwa** [chef-customers/knife-tidy#79]
When running the reports subcommand, `--backup-path` defaults to the current working directory. However, this behavior is not mirrored when running the `clean` subcommand. Instead, tidy will prompt the user for the backup path.

REPRO:
```
knife tidy server report --orgs myorg --node-threshold 90
~$ knife tidy server clean --only-cookbooks
It is not recommended to run this command without specifying a current backup directory.
Please specify a backup directory:
```

**Comment by itmustbejj** [comment]
This is intentional. Generating reports is a non-destructive action, so we are fine assuming the backup directory. With a `knife tidy server clean`, since you are deleting objects on the Chef Server, we are requiring the user to specify their valid backup path as an exercise for the user to confirm there is a valid backup before continuing.

**Comment by jeremymv2** [comment]
Yes, this was intentional to force user's into having a backup on hand prior to running any destructive operations.

**Comment by haidangwa** [comment]
@jeremymv2 This assertion fails, because the code is only checking that the directory exists and is a directory. The directory can actually be empty and the destructive action can still proceed. From what I could find, these are the only two validation checks pertaining to the backup path: https://github.com/chef-customers/knife-tidy/blob/master/lib/chef/knife/tidy_server_clean.rb#L48-L56
